const { Schema, model } = require('mongoose');

module.exports = model(
  'bots',
  new Schema({
    botID: { type: String, default: '00000000000000' },
    botName: { type: String, default: 'Infinity' },
    type: { type: String, default: 'pending' },
    long: { type: String, default: 'No long description' },
    short: { type: String, default: 'No short description' },
    announce_msg: {
      type: String,
      default: "There's not any announcement messages available!",
    },
    servers: { type: Number, default: 0 },
    shards: { type: Number, default: 0 },
    votes: { type: Number, default: 0 },
    clicks: { type: Number, default: 0 },
    invite_clicks: { type: Number, default: 0 },
    sub_period: { type: Number, default: 0 },
    uptime: { type: Number, default: 0 },
    total_uptime: { type: Number, default: 0 },
    website: { type: String, default: 'none' },
    donate: { type: String, default: 'none' },
    invite: { type: String, default: 'none' },
    support: { type: String, default: 'none' },
    github: { type: String, default: 'none' },
    staff: { type: Boolean, default: false },
    announce: { type: Boolean, default: false },
    certified: { type: Boolean, default: false },
    pending_cert: { type: Boolean, default: false },
    nsfw: { type: Boolean, default: false },
    premium: { type: Boolean, default: false },
    cert_reason: { type: String, default: 'none' },
    vanity: { type: String, default: 'none' },
    token: { type: String, default: 'none' },
    webhook: { type: String, default: 'none' },
    note: { type: String, default: 'none' },
    tags: { type: String, default: 'none' },
    library: { type: String, default: 'none' },
    prefix: { type: String, default: 'none' },
    main_owner: { type: String, default: 'none' },
    webAuth: { type: String, default: 'none' },
    webURL: { type: String, default: 'none' },
    start_period: { type: Number, default: Date.now() },
    date: { type: Number, default: Date.now() },
    additional_owners: { type: Array, default: [] },
    background: { type: String, default: 'https://i.imgur.com/lNdMzuW.png' },
    vote_banned: { type: Boolean, default: false },
    claimedBy: { type: String, default: null },
    claimed: { type: Boolean, default: false },
  }),
);
